### ISSUE TITLE
volar's go to definition failed when I added the jsconfig file

### ISSUE THREAD

**Issue by vanchKong** [ElanYoung/vite-vue2-js-starter-template#2]
In [your demo](https://github.com/ElanYoung/vite-vue2-js-starter-template/blob/cd7fdbc0b33867bc7176bbb896e2e7c556b4d6da/src/views/AboutView.vue) here.

In vscode,i couldn't use `CTRL + CLICK` to go to definition, such as [`login function`](https://github.com/ElanYoung/vite-vue2-js-starter-template/blob/cd7fdbc0b33867bc7176bbb896e2e7c556b4d6da/src/views/AboutView.vue#L19).

In my demo[^1], I found that it caused by `jsconfig.json`.(I don't know why,  in your project, even if you delete the `jsconfig.json`, still can't go to the definition.)

If I have some way to resolve it?

[^1]: just use `npm create vue@2`, and code something, add or remove `jsconfig.json` to test it.

**Comment by vanchKong** [comment]
I tried a few things and I managed to solve this problem.
add these two keys.(found form `references.path` in `vite+ts` demo's `tsconfig.json`)

```
"compilerOptions": {
    ...
    "strict": true,
    "moduleResolution": "Node",
}
```

**Comment by ElanYoung** [comment]
> I tried a few things and I managed to solve this problem. add these two keys.(found form `references.path` in `vite+ts` demo's `tsconfig.json`)
> 
> ```
> "compilerOptions": {
>     ...
>     "strict": true,
>     "moduleResolution": "Node",
> }
> ```

👍
